# Generated by Django 4.1 on 2022-09-22 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppSwim', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nadador',
            name='edad',
            field=models.IntegerField(default=18),
        ),
        migrations.AlterField(
            model_name='slot',
            name='duracion',
            field=models.IntegerField(default=45),
        ),
    ]
